### ISSUE TITLE
JS in form input instead of email address

### ISSUE THREAD

**Issue by ivanvermeyen** [Propaganistas/Email-Obfuscator#1]
Hi!

First of all: your package is super handy, I like it alot :)

I'm using the middleware on a Laravel project, but I noticed that when a form field has a default email value, that is also obfuscated and the resulting javascript is echo'd in the form field (like when you have an "edit user" form, or you `redirect()->back()->withInput()`).

Perhaps you could add a check and ignore emails in input fields?

**Comment by Propaganistas** [comment]
Nice catch! Thanks for reporting.
Could you please test the master branch and check if it's working properly?

**Comment by ivanvermeyen** [comment]
Got:

    ErrorException in Obfuscator.php line 46:
    Undefined variable: safeguard

It works when I change [line 27](https://github.com/Propaganistas/Email-Obfuscator/blob/fe4fc55eb5d9dd69c65e28330f8e743da9ac07d0/src/Obfuscator.php#L27):

`$string = preg_replace_callback($pattern, function ($parts) use ($safeguard) {`

Thanks for the fast fix :)

**Comment by Propaganistas** [comment]
Forgot to import indeed.
New release has been rolled out. Thanks.

**Comment by ivanvermeyen** [comment]
Woops forgot the `use ($safeguard)` on line 27 (in the `foreach` loop).

**Comment by Propaganistas** [comment]
Fixed and rerolled v1.0.2

**Comment by ivanvermeyen** [comment]
Working smooth :)
Thanks!
