### ISSUE TITLE
Would be great if email text as link text would not be obfuscated

### ISSUE THREAD

**Issue by juergenweb** [Propaganistas/Email-Obfuscator#12]
Hello,

if I use an email text instead of the email adress as link text, the obfuscation of the text will lead to an error in HTML validator

For example this validates

`
<a href="mailto:myemail@office.com">myemail@office.com</a>
`

but this not because the obfuscator obfuscates the link text

`
<a href="mailto:myemail@office.com">My email</a>
`

So it would be great if the obfuscation only takes place at email addresses (fe. by checking if an @ is present). So the link text "My email" will not be obfuscated.

Its not a big issue and the obfuscation works, but validation fails all the time.

Best regards

**Comment by Propaganistas** [comment]
I quickly added a possible fix for this. Could you checkout the `mailto` branch if it works out for you? Note that the code is untested on my behalf.

**Comment by juergenweb** [comment]
Thanks, but this change leads to no output (empty string). So it removes the whole string.

By the way on line 50 of Obfuscator.php you can remove the attribute "type="text/javascript".

`
$js = '<script type="text/javascript">Rot13.write(' . "'" . str_rot13($parts[0]) . "'" . ');</script>';
`

change to 

`
$js = '<script>Rot13.write(' . "'" . str_rot13($parts[0]) . "'" . ');</script>';
`

The type attribute is no longer valid in HTML5.

Best regards

**Comment by Propaganistas** [comment]
After some thinking I'm afraid this isn't possible with the current version of the javascript.

Decoding currently only takes place when called through `Rot13.write`. All output includes a `<script>` piece to that function. The only way to make this possible using the current implementation is by including a `<script>` tag within the `href` attribute, but this is even more invalid.

Please feel free to suggest an overhaul PR.

**Comment by juergenweb** [comment]
Ok, Thanks. So its not a big problem, because obfuscation works.
