### ISSUE TITLE
Laravel Debugbar prints JS to the screen when you redirect back with an email input.

### ISSUE THREAD

**Issue by ivanvermeyen** [Propaganistas/Email-Obfuscator#2]
Hi,

Just a heads up if you are using [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar) with Email-Obfuscator:

When you `redirect()->back()->withInput();` and an email is auto filled in, then a bunch of code (objects/arrays) is printed at the bottom of the page. When I disable debugbar, everything works as expected.

I'm not sure if this can or should be fixed (might be more of a Debugbar issue?).

I can always load the package in production only.

This is what Debugbar adds to the page... It gets printed out starting at `and `id` <> '1'`, because the obfuscated email value causes syntax errors in their javascript).

```
phpdebugbar.addDataSet({
    "__meta": {
        //..
    },
    "queries": {
        "nb_statements": 4,
        "nb_failed_statements": 0,
        "accumulated_duration": 0.00141,
        "accumulated_duration_str": "1.41ms",
        "statements": [{
            // ...
        }, {
            // ...
        }, {
            "sql": "select count(*) as aggregate from `users` where `email` = '<script type="
            text / javascript">Rot13.write('vina@irezrlra.bet');</script><noscript><span style="unicode - bidi
:
bidi - override;
direction:rtl;
">gro.neyemrev@navi</span></noscript>' and `id` <> '1'", "params"
:
["<script type="text / javascript">Rot13.write('vina@irezrlra.bet');</script><noscript><span style="unicode - bidi
:
bidi - override;
direction:rtl;
">gro.neyemrev@navi</span></noscript>", "1"
],
// ...
```

**Comment by Propaganistas** [comment]
Could you check out the master branch and report back please?
Note that I haven't tested it myself, it is a wild guess.

**Comment by ivanvermeyen** [comment]
Nice! As far as I can tell, everything works as expected now :)

**Comment by Propaganistas** [comment]
New release rolled out (v1.0.3).

**Comment by ivanvermeyen** [comment]
Thanks!
