### ISSUE TITLE
Middleware contract has been removed in Laravel 5.2

### ISSUE THREAD

**Issue by ivanvermeyen** [Propaganistas/Email-Obfuscator#3]
Hi,

In Laravel 5.2 I get an error:

`Interface 'Illuminate\Contracts\Routing\Middleware' not found`

This is because the interface has been [deprecated](https://github.com/illuminate/contracts/commit/c086e4da4c2e4914e421b37f4ed4643abdc1d024) since 5.1 and [removed](https://github.com/illuminate/contracts/commit/02c53f7d5100a32901ed54cd7beaa46d3d06c6e3) in 5.2.

Removing the interface implementation would fix it:

https://github.com/Propaganistas/Email-Obfuscator/blob/master/src/Laravel/Middleware.php#L6-L8

Greetz!

Ivan

**Comment by Propaganistas** [comment]
Fixed.
Thanks for the notification.
