### ISSUE TITLE
Create Mailto: Link w/Obfuscator

### ISSUE THREAD

**Issue by Emirii** [Propaganistas/Email-Obfuscator#6]
Hello. I am using the Twig implementation (with Symfony). I was wondering if there was any way to add a link to the obfuscated email address easily.

So far I tried this, which the inner html in the mailto doesn't work because of the script tags:
```
<a href="mailto:{{ email.address|obfuscateEmail }}">{{ email.address|obfuscateEmail }}</a>
```
and this, which just dumps the whole string as plain text, I tried the twig |raw, but I don't think that will work since Javascript is really outputting the string.
```
{{ '<a href="mailto:' ~ email.address ~ '">' ~ email.address ~ '</a>'|obfuscateEmail|raw}}
```

Thank you for the great plugin!

**Comment by Propaganistas** [comment]
Hi there

Normally the obfuscator scans for mailto anchor tags and parses them correctly. I'm not very proficient in Twig, so this is a dark topic for me as well.

Perhaps you could try assigning the full anchor string to a variable and then do something like `{{ anchorVar|obfuscateEmail }}` ?

I don't have a clue myself why your second example doesn't work, so if you would find any causes, I'd be glad to fix them.

**Comment by Emirii** [comment]
Thank you for giving me an idea. I was trying to concatenate the string, but I forgot one important thing, you have to assign the variable or use parentheses on the string or else the filter only worked on `'</a>'|obfuscateEmail` and ignore the rest.

So this works both ways:
```
{% set emailURL = '<a href="mailto:' ~ email.address ~ '">' ~ email.address ~ '</a>' %}
{{ emailURL|obfuscateEmail }}
```

```
 {{ ('<a href="mailto:' ~ email.address ~ '">' ~ email.address ~ '</a>')|obfuscateEmail }}
```

Not really anything to do with your package, just how Twig works. Figure I would post in case someone else has the same issue. Definitely a derp moment, Thanks!
