### ISSUE TITLE
E-mail is replaced in textareas

### ISSUE THREAD

**Issue by ivanvermeyen** [Propaganistas/Email-Obfuscator#9]
Hello,
It seems e-mail addresses are also being obfuscated in textareas.
Which is a bit problematic in CMS forms :)

**Comment by Propaganistas** [comment]
Hi

Could you please try the `dev-textarea` branch and report back?

**Comment by ivanvermeyen** [comment]
I tried to require a GitHub branch in composer, but didn't succeed... :)
But I've manually added the same change from your commit in my vendor folder and it no longer obfuscates the e-mail in the textarea. 👍

**Comment by Propaganistas** [comment]
Thanks. I've released a new version. Please update to `1.0.7`.
